### ISSUE TITLE
Add coming soon text

### ISSUE THREAD

**Issue by dimasciput** [kartoza/GeoHosting#123]
![image](https://github.com/user-attachments/assets/5669f1aa-18f5-4008-8500-8f54a204f723)

We should add a 'Coming Soon' message somewhere for the upcoming product and probably hide the pricing since it's not relevant yet.

@amyburness do you agree?

**Comment by amyburness** [comment]
Yes I agree

**Comment by meomancer** [comment]
Hi @tinashechiraya 
You can put coming soon flag on each price like below
![Selection_040](https://github.com/user-attachments/assets/f9922520-77da-4e9b-95b9-f2eadfa1261a)

And put the price, maybe **TBA**

**Comment by meomancer** [comment]
This is done
