### ISSUE TITLE
Create Webhook on Jenkins and ArgoCD

### ISSUE THREAD

**Issue by meomancer** [kartoza/GeoHosting#127]
Minimum json payload
```
{
    "app_name":"test",
     "status":<status>,
     "message":<message>,
     "source": "argocd"
}
```
```
{
    "app_name":"test",
     "status":<status>,
     "message":<message>,
     "source": "jenkins"
}
```
API : 
POST https://geohosting.sta.do.kartoza.com/api/webhook/

**Comment by LokoMoloko98** [comment]
The ArgoCD webhook calls go through, but they are to be filtered so that only geonode instance updates on Argocd are sent.
The Jenkins webhook trigger is put on hold until further notice

**Comment by meomancer** [comment]
This is already working fine, thank you @LokoMoloko98
