### ISSUE TITLE
Instances dashboard

### ISSUE THREAD

**Issue by meomancer** [kartoza/GeoHosting#133]
We need an instance dashboard so user can see list of their instance or service that are already deployed here
![Selection_045](https://github.com/user-attachments/assets/d1d856be-3465-4d22-bcf3-c72b3d8faae9)

@LenevJ 
Could you design how the list page will be?
I think we have the design before (on ERPNext), could you put the image here?

@tinashechiraya 
The Instance model is here: https://github.com/kartoza/GeoHosting/blob/main/django_project/geohosting/models/instance.py
Output:
- List of the user instance
- Tests

**Comment by LenevJ** [comment]
@meomancer Is this what you are looking for?
![9Support_Issues](https://github.com/user-attachments/assets/feef3eb5-c9cc-4a71-88cb-2594be4809c4)

**Comment by meomancer** [comment]
Thank you @LenevJ 
Could you implemented this one first @tinashechiraya ?
https://github.com/kartoza/GeoHosting/issues/133#issuecomment-2348959583

**Comment by meomancer** [comment]
The list of instance is done
We need to know how to access the server information to show the detailed one
