### ISSUE TITLE
Services Icons: Updated colours

### ISSUE THREAD

**Issue by LenevJ** [kartoza/GeoHosting#134]
Current icons contain wrong blue. I've changed them. Please find the new ones here.

![GeoNode Logo](https://github.com/user-attachments/assets/0d1c9695-078f-4ce4-aea8-d110726b05d0)
![GeoServer Logo](https://github.com/user-attachments/assets/4ebb063c-8309-4035-bd64-7572d2d54c8d)
![GeoSight Logo](https://github.com/user-attachments/assets/8225fb34-5acd-49fa-a79b-314584954df7)
![G3W Logo](https://github.com/user-attachments/assets/ff909c0d-2d3d-4224-8a16-f4998e0e3dc7)
![BIMS Logo](https://github.com/user-attachments/assets/78128028-26c6-4a17-88f6-cceb56a0008f)

**Comment by meomancer** [comment]
Could you upload in svg, @LenevJ ?
I download it and it is png

Maybe put it somewhere on gdrive?
cc @tinashechiraya

**Comment by LenevJ** [comment]
Oh no! Sorry, didn't realise. Will upload svgs now

**Comment by LenevJ** [comment]
Let me know if there are still issues, please.
![BIMS Logo](https://github.com/user-attachments/assets/496aed6a-1d6f-497e-b1cb-50fd5fef3183)
![GeoServer Logo](https://github.com/user-attachments/assets/60e5b346-eb70-42b9-bd6f-48ce505ce92b)
![GeoSight Logo](https://github.com/user-attachments/assets/e17a946c-5738-43b2-8e26-1af9b63cf83e)
![GeoNode Logo](https://github.com/user-attachments/assets/9f99d432-d697-4ef5-b3e1-1cf829a73b3f)
![G3W Logo](https://github.com/user-attachments/assets/25a45498-4642-4395-8181-90fc51d072e1)

**Comment by meomancer** [comment]
Hi @LenevJ 
Could you review it on dev server? https://geohosting.dev.do.kartoza.com/
And if it is already correct, please close this ticket
