### ISSUE TITLE
UI Styling: Adjustments and Changes

### ISSUE THREAD

**Issue by LenevJ** [kartoza/GeoHosting#140]
@tinashechiraya Please make the following changes
 
 - [Update Product Card Buttons ] Task 1
Button (current button is smaller than it should be) = Should be 220x54
Unavailable product cards need to have "blur" added

Example of what it should look like:
<img width="535" alt="Screenshot 2024-09-17 104014" src="https://github.com/user-attachments/assets/d73cfcc1-b349-463d-822b-a588ed563e21">

 - [Resize "Return to Top" button Arrow ] Task 2
Increase size of arrow in return to top of page button. Current arrow is very small and almost invisible.

Note: Rounded square shape is correct size, arrow in shape should be 20x10.
Example of what it should look like:
<img width="257" alt="Screenshot 2024-09-17 104849" src="https://github.com/user-attachments/assets/d9cca3a7-adb8-47bf-beaa-d39db7486df9">

**Comment by LenevJ** [comment]
@amyburness @tinashechiraya Here is the new logo svg. Please let me know if there are any issues and if I should upload just an svg of the symbol.
![GSH Logo](https://github.com/user-attachments/assets/e63d593b-f728-4dbe-8219-d1c783bbd243)

**Comment by meomancer** [comment]
Hi @LenevJ 
This is updated, please check it
https://geohosting.dev.do.kartoza.com/

**Comment by LenevJ** [comment]
@meomancer Thank you, it looks good
