### ISSUE TITLE
GSH DR Strategy Drill

### ISSUE THREAD

**Issue by LokoMoloko98** [kartoza/GeoHosting#144]
Simulate a Disaster Recovery execution on one of the GSH GeoNode instances by:

1. Abruptly killing an instance that has a significant amount of Geospatial data that has been backed up via Velero
2. Redeploy the same instance from the latest Velero back ups 
3. Have the GIS experts and DevOps monitor performance of the recovered GSH GeoNode instance

**Comment by amyburness** [comment]
@Jeremy-Prior @seabilwe please check the current status. 
@jeremy @seabilwe  we need to check that the restore was successful.

**Comment by Jeremy-Prior** [comment]
@amyburness I'll will check it out

**Comment by Jeremy-Prior** [comment]
All resources back up on site

![image](https://github.com/user-attachments/assets/d8940bb5-3422-4f5e-a4f5-0121a9fec209)

**Comment by LokoMoloko98** [comment]
The `size2` GeoNode instance has undergone the DR drill and is back online. The former credentials are still in place. @seabilwe, @Jeremy-Prior, please check if all the data and configurations that was there before the DR are still in place.

**Comment by Jeremy-Prior** [comment]
GeoNode is up and accounts work for signing in.

The resources are back (datasets, documentation, maps, geostories):
![image](https://github.com/user-attachments/assets/46264f8f-484b-4572-8ec6-47ac7e3a8012)

Different permissions associated with the various resources were also restored:
![image](https://github.com/user-attachments/assets/abfa06c6-a7d6-49f0-b9e0-4b76374f0871)

Raster data and documents appear to be restored however, vector data is not displaying when viewing maps or datasets.
Example on dataset:
![image](https://github.com/user-attachments/assets/b3219d1d-6f0b-4286-801b-8ca0e76e4f9b)

Example on map (the map's annotations were restored correctly):
![image](https://github.com/user-attachments/assets/524d9c6f-c8f3-4c75-b360-13f46ce8eaa8)



@LokoMoloko98, to view the issue:
1. Log in to the GeoNode
2. Click view on a dataset, symbolised by this ![image](https://github.com/user-attachments/assets/5a6b8146-3465-465e-9a0b-bfd6adcc499b)
3. Look at the visualisation and note only the backing map is displayed.

**Comment by Jeremy-Prior** [comment]
Seems to be coming from the geoserver:
![image](https://github.com/user-attachments/assets/524e06b8-720d-4645-a4e4-1e4ef7aa74d1)

Steps to get to error page:
1. Log in to the GeoServer (can be accessed from the GeoNode using the Admin account)
2. Click on layers on the lefthand side
3. On Layers page, click on a layer title
4. On the specific layer's page, click on the publishing tab

**Comment by Jeremy-Prior** [comment]
Additionally, you can't log straight into the geoserver anymore, you need to go from the GeoNode to the GeoServer

**Comment by seabilwe** [comment]
@LokoMoloko98 these are the recent full logs from geoserver
[geoserver.log](https://github.com/user-attachments/files/17072353/geoserver.log)

**Comment by LokoMoloko98** [comment]
Thank's @seabilwe. The recovered version size2 is essentially a `new` deployment and as part of the deployment process credentials were created. From what @Jeremy-Prior and I picked up the creds that word are the:
* old Geonode creds
* new Geoserver server creds 

The logs you posted show that the `kartoza-geonode` user is not being authenticated and it probably because its using the old creds

**Comment by LokoMoloko98** [comment]
@Jeremy-Prior, @seabilwe all good for closing?

cc: @lgkgh

**Comment by Jeremy-Prior** [comment]
@LokoMoloko98, yes. Everything is back online and th layers are appearing. Additionally signing in and out of geonode and the geoserver works correctly.
