### ISSUE TITLE
show terms and conditions before checkout

### ISSUE THREAD

**Issue by tinashechiraya** [kartoza/GeoHosting#160]
user should agree to the terms and conditions before proceeding to the checkout 

- [ ] Add terms and conditions pop up dialog 
- [ ] Show the content

**Comment by gubuntu** [comment]
depends on #119 

ideally this should be integrated with ERP Next in its subscription / contracting modules. Otherwise the Ts and Cs need to be show or linked with a tick box confirming agreement
