### ISSUE TITLE
Set up Kartoza Stripe account

### ISSUE THREAD

**Issue by gubuntu** [kartoza/GeoHosting#168]
We need a Stripe account in Kartoza Lda's name

It must be linked to Kartoza Lda's bank account

**Comment by timlinux** [comment]
@gubuntu what email do you want it linked to?

**Comment by gubuntu** [comment]
@timlinux you mean for the admin account or for notifications. The latter can be statements@kartoza.com. The former I guess should be you, then you give access to me, Juanique etc.
