### ISSUE TITLE
fix support page destination

### ISSUE THREAD

**Issue by gubuntu** [kartoza/GeoHosting#173]
the link to the support page on the GeoNode product page take you back to the home page if you are not logged in. 

If you are logged in it does go to the Django support page. 

If you are not logged in it should go to the login / register page surely?

**Comment by meomancer** [comment]
The issue for this:
![support](https://github.com/user-attachments/assets/7fd2e2a4-5c71-4360-bbfc-308b615deb21)

The solution:
1. Make **create issue** as public function
![Create issue](https://github.com/user-attachments/assets/15826a9e-cd16-4ed6-888c-3d65b7635342)

2. When user click "Support center", user will be create issue modal
![Selection_030](https://github.com/user-attachments/assets/345f2228-84e3-40b1-ba09-362ff8b008c2)

3. Change "customer" to "email"
4. Create communication with that support through email (Is it already being handled by ERP, @voogt )

**Comment by meomancer** [comment]
This is done, the next steps in this ticket 
https://github.com/kartoza/GeoHosting/issues/179
