### ISSUE TITLE
fix customer creation 

### ISSUE THREAD

**Issue by gubuntu** [kartoza/GeoHosting#175]
current behaviour: an ERP customer is created from the user details, in their personal capacity

problem: most customers will be businesses, not individuals

solution: capture company details on registration or on purchase page, with the default option to purchase as the company and a tickbox to say if they are purchasing in their personal capacity. When company details are saved they must create the company as a customer in ERPNext with the user as the billing contact. i.e. The user must not be a customer in ERP unless they are buying in their personal capacity

**Comment by meomancer** [comment]
This is done
Next update is this: https://github.com/kartoza/GeoHosting/issues/197
