### ISSUE TITLE
Split the company address on invoice based on the currency or payment

### ISSUE THREAD

**Issue by meomancer** [kartoza/GeoHosting#198]
# Problem
We need to be able to split company address on invoice based on currency or payment

# Solution
- Do we have company address splitting on SA and Portugal?
- When user paying ZAR use SA address

**Comment by meomancer** [comment]
Do we have this function @voogt ?
What data should be passed by GeoHosting to change it?

**Comment by voogt** [comment]
Hi @meomancer when you create a sales order you can specify the field `company` to be either `Kartoza Lda` or `Kartoza (Pty) Ltd ` ERP should take care of address splitting depending on what company you chose to create the sales order
