### ISSUE TITLE
Access Stripe Account for Payment Integration

### ISSUE THREAD

**Issue by dimasciput** [kartoza/GeoHosting#45]
From @meomancer 

> Hi @EliVolsch  we need kartoza stripe account for payment, could you ask if we have it?
We need the test mode and needs Public and Secret keys

**Comment by gubuntu** [comment]
we are using Paystack, not Stripe, for ZAR shopfront. Juanique has already integrated paystack with ERP. 

For a EUR shopfront with a Kartoza Lda ERP backend, we might be able to use Stripe.

**Comment by dimasciput** [comment]
@gubuntu Yes, this is for non-SA. We are going to offer multiple payment methods.

**Comment by amyburness** [comment]
to confirm @meomancer @dimasciput @gubuntu 

We will be using PayStack for South African Payments and Stripe for international. This is what we will implement for MVP (we can always incorporate PayPal as a payment option later for the next version but don't spend time on it now).
we can use an API for communicate with ERP from Stripe.

**Comment by meomancer** [comment]
This is done, i have access to Kartoza stripe account
