### ISSUE TITLE
Update the current GeoHosting logo

### ISSUE THREAD

**Issue by dimasciput** [kartoza/GeoHosting#48]
![image](https://github.com/user-attachments/assets/d308a38c-02b0-43b3-a586-e9b214a0fa49)

**Comment by LenevJ** [comment]
Changed colour (black to grey), typography, globe icon and sizing. 

![Image](https://github.com/user-attachments/assets/484eec52-b6aa-4d14-8334-882ed994a05a)

**Comment by LenevJ** [comment]
Tried different logo versions that still incorporate the globe. I have a few other logo ideas that I will show here once I'm done with them.

![Image](https://github.com/user-attachments/assets/1e72ee7b-526a-4324-9a92-9b899209a9a7)

**Comment by LenevJ** [comment]
![Uploading Logo Option.png…]()

**Comment by LenevJ** [comment]
<img width="1075" alt="Logo Option" src="https://github.com/user-attachments/assets/73b49c70-1f63-4fb8-a8a2-27451df5acec">

**Comment by LenevJ** [comment]
Rough Idea (perspective is a bit off, but can be fixed if chosen).
<img width="1075" alt="Logo Option 2" src="https://github.com/user-attachments/assets/a334fd71-bac4-419c-891f-80665bde2541">

**Comment by dimasciput** [comment]
@LenevJ I like the last one!

**Comment by LenevJ** [comment]
Great, I'll spend time refining it and then I'll upload it once I'm done.

**Comment by LenevJ** [comment]
Here is the refined logo. Let me know if something needs to be changed/adjusted.

![Image](https://github.com/user-attachments/assets/bc15c2e4-1334-4fbe-81a5-7510b5cdb596)

**Comment by dimasciput** [comment]
@LenevJ hmm, I think I prefer the rough idea better

![image](https://github.com/user-attachments/assets/169bc952-2905-4122-a752-10b6d0323df6)

Perhaps just make the text smaller. Or actually we don't need the text. Just the logo I think.

**Comment by LenevJ** [comment]
![GeoHostingNewLogo_Favicon](https://github.com/user-attachments/assets/aa6553e1-a523-48ff-a44f-50db86dc8571)
Here is the rough idea (I refined it slightly)

**Comment by LenevJ** [comment]
![GeoHostingNewLogo](https://github.com/user-attachments/assets/a39526a7-5bd8-4ab4-b765-9f1a8c3829b7)

**Comment by dimasciput** [comment]
@LenevJ do you have the svg format for the logo only?

**Comment by LenevJ** [comment]
@dimasciput I forgot to export one, will upload the svg version when I have a moment.

**Comment by dimasciput** [comment]
@LenevJ what is font do you use for the title?

**Comment by LenevJ** [comment]
@dimasciput I used Avenir for the title and Lato for the slogan. It was originally Jost and something else, but I changed it to Avenir and Lato since those are the two fonts Kartoza uses, although technically we mainly use Lato for web and Avenir in print stuff.

**Comment by LenevJ** [comment]
Here is the svg for the logo icon.
![GeoHostingLogo-04](https://github.com/user-attachments/assets/60ab59da-ec68-4bb9-9606-452be00db2aa)
