### ISSUE TITLE
Update GeoHosting Background

### ISSUE THREAD

**Issue by dimasciput** [kartoza/GeoHosting#52]

**Comment by LenevJ** [comment]
The idea I had for the background was to still show "geography" but try and combine it with "data" and show an areal view of a city/town as components, etc. I also think we should include a little introduction paragraph to the top of GeoHosting page to explain the what/why (ignore the filler text paragraph) and I realise we technically don't have a footer yet, so I just used the Kartoza website one as a filler to get the overall effect. 
![Idea](https://github.com/user-attachments/assets/2727ee9c-a61b-4576-897a-35f21b899753)

**Comment by LenevJ** [comment]
Should I explore this idea further or try something completely different?

**Comment by dimasciput** [comment]
Hi @LenevJ 

I think the background is too cluttered for me. What do you think? 

Or could you try using the existing Kartoza background but make it an outline instead of a fill to make it more modern?

As for the footer, I think your version is much better than what we had before. Let's use this for now.

**Comment by LenevJ** [comment]
@dimasciput I'll implement the changes you suggested and upload the designs once they are done.

**Comment by LenevJ** [comment]
@dimasciput 

I tried the ouline version like you suggested, but now it feels a bit too empty. I'm going to play around with opacity a bit for a third option. 

![Option 1](https://github.com/user-attachments/assets/36cf44e4-f48c-43a4-bc4c-c49301d42ebb)
![Option 2](https://github.com/user-attachments/assets/4195bec1-6f3f-4653-8cd7-f3b457e20b2e)

**Comment by dimasciput** [comment]
@LenevJ, I think the first option is quite minimalist and looks good. Should we try that one first? I think leaving some empty space for now is fine. If the client doesn't like it, we can always change it later. Could you make the background high resolution?

**Comment by LenevJ** [comment]
@dimasciput I hear you. I'll get the high res version uploaded here soon. Sent as an SVG correct?

**Comment by LenevJ** [comment]
Here is the SVG for the thin outline version of the background. Let me know if there is resolution issues.
![GeoSpatialHosting_ThinMinimalistBackground-05](https://github.com/user-attachments/assets/9a76a17c-2570-44a3-90bc-fe1dbafba3c1)

**Comment by LenevJ** [comment]
Here is a slightly thicker outline as another option.
![GeoSpatialHosting_MinimalistBackground-05](https://github.com/user-attachments/assets/9828e827-b3c4-4a49-a5ad-507985aecd18)

**Comment by LenevJ** [comment]
@dimasciput Here is the left and right seperately, I also added the single design that makes up the left and right side repitition if you need it.

![GeoHostingBackgroundLeft](https://github.com/user-attachments/assets/390a4ad5-0138-4123-a02c-2a4babbfa918)
![GeoHostingBackgroundRight](https://github.com/user-attachments/assets/7fba9e24-7e79-4399-ba04-7bfd2ad20753)
![BackgroundElement](https://github.com/user-attachments/assets/fb943201-4160-4b22-8e8a-5bc400697167)

**Comment by LenevJ** [comment]
@dimasciput Here you go: Left side
![GeoHostingBackgroundLeft](https://github.com/user-attachments/assets/37b4c27e-e8fb-4704-9b04-85a14f162904)

**Comment by LenevJ** [comment]
Here you go: Right side
![GeoHostingBackgroundRight](https://github.com/user-attachments/assets/ca0d9d53-d1b8-4df7-97a0-29281551fc90)

**Comment by LenevJ** [comment]
Incase you need just one single element.
![BackgroundElement](https://github.com/user-attachments/assets/4e7f50fa-b14e-4e33-b7a1-757f6f42903a)

**Comment by LenevJ** [comment]
![BackgroundElementRight](https://github.com/user-attachments/assets/d97e316d-11b1-4f65-b30c-da2cf1c361fe)
![BackgroundElementLeft](https://github.com/user-attachments/assets/7e33f912-585f-4ae4-b21d-be5b4417fe12)
