### ISSUE TITLE
Create and test checkout workflow

### ISSUE THREAD

**Issue by dimasciput** [kartoza/GeoHosting#68]
Review the checkout workflow to identify issues or improvements.

**Comment by EliVolsch** [comment]
@dimasciput 

This is what I believe the checkout workflow should look like.  In this diagram I tried to keep all processes as manual as possible, however some simply cannot be done manually (specifically ERP) as this would add too many points of possible failure. 

![Simple-workflow](https://github.com/user-attachments/assets/a6df7fc3-d60d-4de3-8e35-6f4b8da94061)

In this diagram I mention a "purchase summary" view/page. I believe this might be a perfect pivot point for users, who require a quote, to be able to generate a quote. The logic requires users to enter billing information which can then be used on the quotation document, and when creating a new customer in ERP. The functionality is similar to that on the shopping cart page on kartoza, however users won't be able to add another product.

![image](https://github.com/user-attachments/assets/e04b0cbe-1633-4906-8652-6e9dea52c260)

 From what I have gathered the following information is required by the various departments. Paystack information is to be displayed on invoice generated, ERP info standard information requested from clients, and devops for general admin (keeping track of projects).

![Info](https://github.com/user-attachments/assets/5217e34b-ba4a-489b-83e2-e3996690a907)

Below is a more complex diagram of the first one. In all instances once a user has successfully purchased a new product, they should be redirected to the user portal, where they will be able to find invoices and see their order's build status. 
  
![Purchace-workflow-logic](https://github.com/user-attachments/assets/fa37581c-b965-4a2d-bd94-9e1b5059b18f)

![Geohisting-logic-diagram drawio](https://github.com/user-attachments/assets/a88e3960-0a44-4258-a673-fe255c8ca31a)

Please reach out if you have any questions, queries or comments.

**Comment by gubuntu** [comment]
isn't this done? Close?

**Comment by meomancer** [comment]
We can close this for now and raise after MVP
